# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt6 UI code generator 6.2.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets

class Ui_connectionWindow(object):
    def setupUi(self, connectionWindow):
        connectionWindow.setObjectName("connectionWindow")
        connectionWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(connectionWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(320, 180, 158, 206))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetMaximumSize)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lblNomUtilisateur = QtWidgets.QLabel(self.layoutWidget)
        self.lblNomUtilisateur.setObjectName("lblNomUtilisateur")
        self.verticalLayout.addWidget(self.lblNomUtilisateur)
        self.lndtNomUtilisateur = QtWidgets.QLineEdit(self.layoutWidget)
        self.lndtNomUtilisateur.setObjectName("lndtNomUtilisateur")
        self.verticalLayout.addWidget(self.lndtNomUtilisateur)
        self.lblMdp = QtWidgets.QLabel(self.layoutWidget)
        self.lblMdp.setObjectName("lblMdp")
        self.verticalLayout.addWidget(self.lblMdp)
        self.lndtMdp = QtWidgets.QLineEdit(self.layoutWidget)
        self.lndtMdp.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lndtMdp.setObjectName("lndtMdp")
        self.verticalLayout.addWidget(self.lndtMdp)
        self.rappelCheckBox = QtWidgets.QCheckBox(self.layoutWidget)
        self.rappelCheckBox.setObjectName("rappelCheckBox")
        self.verticalLayout.addWidget(self.rappelCheckBox)
        self.btnConnexion = QtWidgets.QPushButton(self.layoutWidget)
        self.btnConnexion.setStyleSheet("\n"
"    color: #fff;\n"
"    background-color: #0d6efd;\n"
"    border-color: #0d6efd;\n"
"    border-radius: 10px;\n"
"")
        self.btnConnexion.setObjectName("btnConnexion")
        self.verticalLayout.addWidget(self.btnConnexion)
        self.lblErreurIdentifiants = QtWidgets.QLabel(self.centralwidget)
        self.lblErreurIdentifiants.setGeometry(QtCore.QRect(240, 390, 331, 51))
        self.lblErreurIdentifiants.setStyleSheet("color: #dc3545;")
        self.lblErreurIdentifiants.setText("")
        self.lblErreurIdentifiants.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblErreurIdentifiants.setObjectName("lblErreurIdentifiants")
        connectionWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(connectionWindow)
        QtCore.QMetaObject.connectSlotsByName(connectionWindow)

    def retranslateUi(self, connectionWindow):
        _translate = QtCore.QCoreApplication.translate
        connectionWindow.setWindowTitle(_translate("connectionWindow", "connectionWindow"))
        self.lblNomUtilisateur.setText(_translate("connectionWindow", "Nom utilisateur :"))
        self.lblMdp.setText(_translate("connectionWindow", "Mot de passe :"))
        self.rappelCheckBox.setText(_translate("connectionWindow", "Se rappeler de moi"))
        self.btnConnexion.setText(_translate("connectionWindow", "Connexion"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    connectionWindow = QtWidgets.QMainWindow()
    ui = Ui_connectionWindow()
    ui.setupUi(connectionWindow)
    connectionWindow.show()
    sys.exit(app.exec())
