# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt6 UI code generator 6.2.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(811, 681)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setStyleSheet("#MainWindow {\n"
"    margin: 0px;\n"
"padding! 0px\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widHeader = QtWidgets.QWidget(self.centralwidget)
        self.widHeader.setMaximumSize(QtCore.QSize(16777215, 100))
        self.widHeader.setStyleSheet("* {\n"
"    background-color: white;\n"
"}\n"
"\n"
"/*boutons :*/\n"
"#wButtons {\n"
"    max-width: 400px;\n"
"}\n"
"\n"
"#btnClubs {\n"
"    max-width: 80px;\n"
"\n"
"}\n"
"#btnTitulaires {\n"
"    max-width: 105px;\n"
"}\n"
"#btnChampoinnat {\n"
"    max-width: 150px;\n"
"}\n"
"\n"
"#btnDeconnexion {\n"
"    color: #dc3545;\n"
"    border: 1px solid #dc3545;\n"
"    border-radius:5px;\n"
"}\n"
"\n"
"#btnDeconnexion:hover {\n"
"    background-color: #dc3545;\n"
"    color: white;\n"
"}")
        self.widHeader.setObjectName("widHeader")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widHeader)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widLogo = QtWidgets.QWidget(self.widHeader)
        self.widLogo.setMaximumSize(QtCore.QSize(230, 16777215))
        self.widLogo.setObjectName("widLogo")
        self.verticalLayoutLogo = QtWidgets.QVBoxLayout(self.widLogo)
        self.verticalLayoutLogo.setObjectName("verticalLayoutLogo")
        self.lblLogo = QtWidgets.QLabel(self.widLogo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblLogo.sizePolicy().hasHeightForWidth())
        self.lblLogo.setSizePolicy(sizePolicy)
        self.lblLogo.setMinimumSize(QtCore.QSize(200, 55))
        self.lblLogo.setAutoFillBackground(False)
        self.lblLogo.setStyleSheet("")
        self.lblLogo.setText("")
        self.lblLogo.setPixmap(QtGui.QPixmap("./img/logo.svg"))
        self.lblLogo.setScaledContents(True)
        self.lblLogo.setObjectName("lblLogo")
        self.verticalLayoutLogo.addWidget(self.lblLogo)
        self.horizontalLayout.addWidget(self.widLogo)
        self.widButtons = QtWidgets.QWidget(self.widHeader)
        self.widButtons.setObjectName("widButtons")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widButtons)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btnClubs = QtWidgets.QPushButton(self.widButtons)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnClubs.sizePolicy().hasHeightForWidth())
        self.btnClubs.setSizePolicy(sizePolicy)
        self.btnClubs.setMinimumSize(QtCore.QSize(80, 0))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btnClubs.setFont(font)
        self.btnClubs.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnClubs.setStyleSheet("color: rgba(0, 0, 0, .55);\n"
"border: none;")
        self.btnClubs.setObjectName("btnClubs")
        self.horizontalLayout_2.addWidget(self.btnClubs)
        self.btnTitulaires = QtWidgets.QPushButton(self.widButtons)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnTitulaires.sizePolicy().hasHeightForWidth())
        self.btnTitulaires.setSizePolicy(sizePolicy)
        self.btnTitulaires.setMinimumSize(QtCore.QSize(105, 0))
        self.btnTitulaires.setMaximumSize(QtCore.QSize(105, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btnTitulaires.setFont(font)
        self.btnTitulaires.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnTitulaires.setStyleSheet("color: rgba(0, 0, 0, .55);\n"
"cursor: pointer;\n"
"border: none;")
        self.btnTitulaires.setObjectName("btnTitulaires")
        self.horizontalLayout_2.addWidget(self.btnTitulaires)
        self.btnChampionnats = QtWidgets.QPushButton(self.widButtons)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnChampionnats.sizePolicy().hasHeightForWidth())
        self.btnChampionnats.setSizePolicy(sizePolicy)
        self.btnChampionnats.setMinimumSize(QtCore.QSize(150, 0))
        self.btnChampionnats.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btnChampionnats.setFont(font)
        self.btnChampionnats.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnChampionnats.setStyleSheet("color: rgba(0, 0, 0, .55);\n"
"cursor: pointer;\n"
"border: none;")
        self.btnChampionnats.setObjectName("btnChampionnats")
        self.horizontalLayout_2.addWidget(self.btnChampionnats)
        self.horizontalLayout.addWidget(self.widButtons)
        self.widDeconnexion = QtWidgets.QWidget(self.widHeader)
        self.widDeconnexion.setObjectName("widDeconnexion")
        self.verticalLayoutDeconnexion = QtWidgets.QVBoxLayout(self.widDeconnexion)
        self.verticalLayoutDeconnexion.setObjectName("verticalLayoutDeconnexion")
        self.btnDeconnexion = QtWidgets.QPushButton(self.widDeconnexion)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnDeconnexion.sizePolicy().hasHeightForWidth())
        self.btnDeconnexion.setSizePolicy(sizePolicy)
        self.btnDeconnexion.setMinimumSize(QtCore.QSize(150, 50))
        self.btnDeconnexion.setMaximumSize(QtCore.QSize(150, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btnDeconnexion.setFont(font)
        self.btnDeconnexion.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnDeconnexion.setAutoFillBackground(False)
        self.btnDeconnexion.setStyleSheet("")
        self.btnDeconnexion.setObjectName("btnDeconnexion")
        self.verticalLayoutDeconnexion.addWidget(self.btnDeconnexion)
        self.horizontalLayout.addWidget(self.widDeconnexion, 0, QtCore.Qt.AlignmentFlag.AlignRight)
        self.verticalLayout.addWidget(self.widHeader)
        self.widBody = QtWidgets.QWidget(self.centralwidget)
        self.widBody.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widBody.setStyleSheet("")
        self.widBody.setObjectName("widBody")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widBody)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.widStacked = QtWidgets.QStackedWidget(self.widBody)
        self.widStacked.setStyleSheet("#lblAddTitulaire{\n"
"    font-weight: 200;\n"
"    font-family: open-sans;\n"
"    font-size: 25px;\n"
"    color: #212529;\n"
"\n"
"}\n"
"\n"
"#tituLeft {\n"
"    background-color : #E9ECEF;\n"
"}\n"
"\n"
"")
        self.widStacked.setObjectName("widStacked")
        self.widClubs = QtWidgets.QWidget()
        self.widClubs.setObjectName("widClubs")
        self.pushButton_2 = QtWidgets.QPushButton(self.widClubs)
        self.pushButton_2.setGeometry(QtCore.QRect(200, 50, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.widStacked.addWidget(self.widClubs)
        self.widTitulaires = QtWidgets.QWidget()
        self.widTitulaires.setObjectName("widTitulaires")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widTitulaires)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.tituLeft = QtWidgets.QWidget(self.widTitulaires)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tituLeft.sizePolicy().hasHeightForWidth())
        self.tituLeft.setSizePolicy(sizePolicy)
        self.tituLeft.setMinimumSize(QtCore.QSize(0, 500))
        self.tituLeft.setMaximumSize(QtCore.QSize(400, 800))
        self.tituLeft.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.tituLeft.setStyleSheet("* {\n"
"color: grey;\n"
"}")
        self.tituLeft.setObjectName("tituLeft")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.tituLeft)
        self.verticalLayout_8.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.widTitulairesTitle = QtWidgets.QWidget(self.tituLeft)
        self.widTitulairesTitle.setStyleSheet("color: black;")
        self.widTitulairesTitle.setObjectName("widTitulairesTitle")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widTitulairesTitle)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.lblAddTitulaire = QtWidgets.QLabel(self.widTitulairesTitle)
        self.lblAddTitulaire.setMaximumSize(QtCore.QSize(16777215, 100))
        self.lblAddTitulaire.setStyleSheet("color: grey;")
        self.lblAddTitulaire.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblAddTitulaire.setObjectName("lblAddTitulaire")
        self.verticalLayout_6.addWidget(self.lblAddTitulaire)
        self.verticalLayout_8.addWidget(self.widTitulairesTitle)
        self.widget = QtWidgets.QWidget(self.tituLeft)
        self.widget.setObjectName("widget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.t_lblName = QtWidgets.QLabel(self.widget)
        self.t_lblName.setMaximumSize(QtCore.QSize(16777215, 10))
        font = QtGui.QFont()
        self.t_lblName.setFont(font)
        self.t_lblName.setObjectName("t_lblName")
        self.verticalLayout_5.addWidget(self.t_lblName)
        self.t_txtName = QtWidgets.QTextEdit(self.widget)
        self.t_txtName.setMinimumSize(QtCore.QSize(0, 30))
        self.t_txtName.setMaximumSize(QtCore.QSize(16777215, 30))
        self.t_txtName.setStyleSheet("color: red;\n"
"-webkit-text-security: disc; \n"
"")
        self.t_txtName.setPlaceholderText("")
        self.t_txtName.setObjectName("t_txtName")
        self.verticalLayout_5.addWidget(self.t_txtName)
        self.t_lblFName = QtWidgets.QLabel(self.widget)
        self.t_lblFName.setMaximumSize(QtCore.QSize(16777215, 10))
        font = QtGui.QFont()
        self.t_lblFName.setFont(font)
        self.t_lblFName.setObjectName("t_lblFName")
        self.verticalLayout_5.addWidget(self.t_lblFName)
        self.t_txtFName = QtWidgets.QTextEdit(self.widget)
        self.t_txtFName.setMinimumSize(QtCore.QSize(0, 30))
        self.t_txtFName.setMaximumSize(QtCore.QSize(16777215, 30))
        self.t_txtFName.setStyleSheet("color: black;")
        self.t_txtFName.setPlaceholderText("")
        self.t_txtFName.setObjectName("t_txtFName")
        self.verticalLayout_5.addWidget(self.t_txtFName)
        self.t_lblBirthDate = QtWidgets.QLabel(self.widget)
        self.t_lblBirthDate.setMaximumSize(QtCore.QSize(16777215, 10))
        font = QtGui.QFont()
        self.t_lblBirthDate.setFont(font)
        self.t_lblBirthDate.setObjectName("t_lblBirthDate")
        self.verticalLayout_5.addWidget(self.t_lblBirthDate)
        self.t_birthDate = QtWidgets.QDateEdit(self.widget)
        self.t_birthDate.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        self.t_birthDate.setFont(font)
        self.t_birthDate.setStyleSheet("color: black;")
        self.t_birthDate.setObjectName("t_birthDate")
        self.verticalLayout_5.addWidget(self.t_birthDate)
        self.t_lblClub = QtWidgets.QLabel(self.widget)
        self.t_lblClub.setMaximumSize(QtCore.QSize(16777215, 10))
        font = QtGui.QFont()
        self.t_lblClub.setFont(font)
        self.t_lblClub.setObjectName("t_lblClub")
        self.verticalLayout_5.addWidget(self.t_lblClub)
        self.t_listClub = QtWidgets.QComboBox(self.widget)
        self.t_listClub.setMinimumSize(QtCore.QSize(0, 30))
        self.t_listClub.setMaximumSize(QtCore.QSize(16777215, 30))
        self.t_listClub.setObjectName("t_listClub")
        self.verticalLayout_5.addWidget(self.t_listClub)
        self.t_lblPlaque = QtWidgets.QLabel(self.widget)
        self.t_lblPlaque.setMaximumSize(QtCore.QSize(16777215, 10))
        self.t_lblPlaque.setObjectName("t_lblPlaque")
        self.verticalLayout_5.addWidget(self.t_lblPlaque)
        self.t_txtPlaque = QtWidgets.QTextEdit(self.widget)
        self.t_txtPlaque.setMinimumSize(QtCore.QSize(0, 30))
        self.t_txtPlaque.setMaximumSize(QtCore.QSize(16777215, 30))
        self.t_txtPlaque.setStyleSheet("color: black;")
        self.t_txtPlaque.setPlaceholderText("")
        self.t_txtPlaque.setObjectName("t_txtPlaque")
        self.verticalLayout_5.addWidget(self.t_txtPlaque)
        self.t_lblSexe = QtWidgets.QLabel(self.widget)
        self.t_lblSexe.setMaximumSize(QtCore.QSize(16777215, 10))
        self.t_lblSexe.setObjectName("t_lblSexe")
        self.verticalLayout_5.addWidget(self.t_lblSexe)
        self.comboBox = QtWidgets.QComboBox(self.widget)
        self.comboBox.setMinimumSize(QtCore.QSize(0, 30))
        self.comboBox.setMaximumSize(QtCore.QSize(16777215, 30))
        self.comboBox.setObjectName("comboBox")
        self.verticalLayout_5.addWidget(self.comboBox)
        self.verticalLayout_8.addWidget(self.widget)
        self.widBtnAdd = QtWidgets.QWidget(self.tituLeft)
        self.widBtnAdd.setStyleSheet("#t_btnAdd {\n"
"    background-color: white;\n"
"    color: #0d6efd;\n"
"    border: 1px solid #0d6efd;\n"
"    border-radius: 5px;\n"
"    font-size: 15px;\n"
"}\n"
"#t_btnAdd:hover {\n"
"    background-color:#0d6efd ;\n"
"    color:  white;\n"
"}")
        self.widBtnAdd.setObjectName("widBtnAdd")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.widBtnAdd)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.t_btnAdd = QtWidgets.QPushButton(self.widBtnAdd)
        self.t_btnAdd.setMinimumSize(QtCore.QSize(100, 35))
        self.t_btnAdd.setMaximumSize(QtCore.QSize(100, 35))
        self.t_btnAdd.setStyleSheet("")
        self.t_btnAdd.setObjectName("t_btnAdd")
        self.verticalLayout_7.addWidget(self.t_btnAdd, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.verticalLayout_8.addWidget(self.widBtnAdd)
        self.horizontalLayout_3.addWidget(self.tituLeft, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        self.tituRight = QtWidgets.QWidget(self.widTitulaires)
        self.tituRight.setMinimumSize(QtCore.QSize(0, 30))
        self.tituRight.setObjectName("tituRight")
        self.pushButton_3 = QtWidgets.QPushButton(self.tituRight)
        self.pushButton_3.setGeometry(QtCore.QRect(70, 110, 75, 24))
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_3.addWidget(self.tituRight)
        self.widStacked.addWidget(self.widTitulaires)
        self.widChampionnats = QtWidgets.QWidget()
        self.widChampionnats.setObjectName("widChampionnats")
        self.pushButton = QtWidgets.QPushButton(self.widChampionnats)
        self.pushButton.setGeometry(QtCore.QRect(290, 100, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.widStacked.addWidget(self.widChampionnats)
        self.verticalLayout_4.addWidget(self.widStacked)
        self.verticalLayout.addWidget(self.widBody)
        MainWindow.setCentralWidget(self.centralwidget)
        self.actionoui = QtGui.QAction(MainWindow)
        self.actionoui.setObjectName("actionoui")

        self.retranslateUi(MainWindow)
        self.widStacked.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Ufolep - BMX Race"))
        self.btnClubs.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Club</span></p></body></html>"))
        self.btnClubs.setText(_translate("MainWindow", "Clubs"))
        self.btnTitulaires.setText(_translate("MainWindow", "Titulaires"))
        self.btnChampionnats.setText(_translate("MainWindow", "Championnats"))
        self.btnDeconnexion.setText(_translate("MainWindow", "Déconnexion"))
        self.pushButton_2.setText(_translate("MainWindow", "non"))
        self.lblAddTitulaire.setText(_translate("MainWindow", "Ajouter un titulaire"))
        self.t_lblName.setText(_translate("MainWindow", "Nom"))
        self.t_txtName.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:8.25pt;\"><br /></p></body></html>"))
        self.t_lblFName.setText(_translate("MainWindow", "Prénom"))
        self.t_lblBirthDate.setText(_translate("MainWindow", "Date de naissance"))
        self.t_lblClub.setText(_translate("MainWindow", "Club"))
        self.t_lblPlaque.setText(_translate("MainWindow", "Numéro de plaque"))
        self.t_lblSexe.setText(_translate("MainWindow", "Sexe"))
        self.t_btnAdd.setText(_translate("MainWindow", "Ajouter"))
        self.pushButton_3.setText(_translate("MainWindow", "PushButton"))
        self.pushButton.setText(_translate("MainWindow", "oui"))
        self.actionoui.setText(_translate("MainWindow", "oui"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
